### ISSUE TITLE
Support for passing in stats options?

### ISSUE THREAD

**Issue by julianguyen** [relative-ci/rollup-plugin-webpack-stats#107]
It looks like there's no support for being able to pass in [stats.options](https://webpack.js.org/configuration/stats/#stats-options). I see the project is under active development, is this going to be added?

**Comment by vio** [comment]
hi @julianguyen, thanks for opening a ticket! Adding support for the stats options was next on my list, mainly `excludeAssets` and `excludeModules`. 

Is there any other particular option that you are interested in?

**Comment by julianguyen** [comment]
That's great to hear, and thank you! I'd like to see options for enabling and disabling `assets`, `chunks`, and `modules`.

**Comment by vio** [comment]
I think that is not a lot of extra work to include those flags as well. Will leave this one open until we resolve the issue.

Out of curiosity, can you share your use case? We built this plugin as a quick way to support rollup on bundle-stats/relative-ci, and assets/chunks/modules are always included.

**Comment by julianguyen** [comment]
Thank you! My use case is being able to filter out information that's not needed when uploading the output to observability and monitoring tools.

**Comment by vio** [comment]
`excludeAssets` and `excludeModule` [options](https://github.com/relative-ci/rollup-plugin-webpack-stats?tab=readme-ov-file#options) are now available in [`v0.4.0`](https://github.com/relative-ci/rollup-plugin-webpack-stats/releases/tag/v0.4.0).

Feel free to open a new issue for other webpack stats options ;)
