### ISSUE TITLE
Sourcemaps should not be marked as assets

### ISSUE THREAD

**Issue by BPScott** [relative-ci/rollup-plugin-webpack-stats#259]
### Expected behaviour

In a webpack build stats output the `assets` array does not contain `.map` files.

Sourcemaps are attached to the asset that they refer to in the "related" array:

```
assets: [
  {
    name: "134.latest.en.530db1e5a27abfe65cfe.js",
    related: [
      {name: "134.latest.en.530db1e5a27abfe65cfe.js.map"}
    ]
  }
]

```

### Actual behavior

In a `rollup-plugin-webpack-stats` build stats output the assets array contains map files

```
assets: [
  {
    name: "134.latest.en.530db1e5a27abfe65cfe.js",
  },
  {
    name: "134.latest.en.530db1e5a27abfe65cfe.js.map"
  }
]
```

### Fix

Ideally the output would match webpack - with the `related` array being populated with sourcemaps.

That said I don't know if stats analysis tools make use of the related array, so perhaps it'd be ok to just skip processing sourcemaps rather than trying to connect them to the assets that they're sourcemap of.

**Comment by vio** [comment]
@BPScott, I can't remember seeing "related" used in any of the tools, but since it is new(introduced in webpack v5), bundle-stats is filtering the ".map" assets before analyzing.

In case you want to skip it directly from the output of the plugin, you should be able to use [`excludeAssets`](https://github.com/relative-ci/rollup-plugin-webpack-stats/issues/108#issue-1940830686) option soon.

**Comment by vio** [comment]
Added support for `excludeAssets` and `excludeModules` [options](https://github.com/relative-ci/rollup-plugin-webpack-stats?tab=readme-ov-file#options) in [`v0.4.0`](https://github.com/relative-ci/rollup-plugin-webpack-stats/releases/tag/v0.4.0).

To ignore all the `.map` files, pass the `excludeAssets: /\.map$/` option to the plugin:

```js
// rollup.config.js
const { webpackStats } = require('rollup-plugin-webpack-stats');

module.exports = {
  plugins: [
    // add it as the last plugin
    webpackStats({
      excludeAssets: /\.map$/,
    }),
  ],
};
```
