### ISSUE TITLE
v1 Error: `To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

### ISSUE THREAD

**Issue by marekdedic** [relative-ci/rollup-plugin-webpack-stats#279]
Hi,
I'm getting the error from the title when updating to v1, see marekdedic/imagelightbox#1009

**Comment by vio** [comment]
@marekdedic type:module is affecting the cjs/mjs resolution for our example: https://github.com/relative-ci/example-vite-github-action/actions/runs/9668111073/job/26671521205. 

I couldn't spot the difference between your setup and ours, but in the meantime, I released `v1.0.1-beta.1` with explicit cjs/mjs extensions. If you get the chance, can you please give it a try?

**Comment by marekdedic** [comment]
Hmm, that's weird, it seems like the example can't find the CJS version. My package actually has a CJS & ESM build as well, [here](https://github.com/marekdedic/imagelightbox/blob/8e5197984f0d4cf915d387c257d2b48fbb15bd36/package.json#L8-L24)'s the config. It seems similar with one difference that may be important - your CJS file is `.cjs.js` - I think it should be just `.cjs` - that way Node always interprets it as a CJS file. When it's just `.js`, the interpretation depends on the `type` property in `package.json`, which is probably why #280 breaks it?

**Comment by vio** [comment]
@marekdedic you are right about the difference, type: module is changing the way modules are resolved. I did not see the error on our example or other projects because most of them are apps and they do not need a type: module.

Let me know if `v1.0.1-beta.1` works as expected for you.

**Comment by marekdedic** [comment]
Yeah, sorry, can confirm the beta works for me :)

**Comment by vio** [comment]
@marekdedic thanks for checking! The fix is now available on `v1.0.1`
