### ISSUE TITLE
Latest version not released to npm

### ISSUE THREAD

**Issue by skovhus** [relative-ci/rollup-plugin-webpack-stats#398]
https://www.npmjs.com/package/rollup-plugin-webpack-stats is stuck on 1.1.1, although https://github.com/relative-ci/rollup-plugin-webpack-stats/releases/tag/v1.2.1 was recently released.

**Comment by vio** [comment]
Thank you for opening an issue, @skovhus!  

I noticed the release flow skipped the npm publish workflow for the last 2 versions, I am looking into it.

**Comment by vio** [comment]
Fixed the workflow config and released [`v1.2.3`](https://www.npmjs.com/package/rollup-plugin-webpack-stats/v/1.2.3).

@skovhus  Thanks again for opening the issue! Feel free to reach out if you notice any issues ;)

**Comment by skovhus** [comment]
Thanks for fixing!
